- lib/elastic_whenever/schedule.rb
- lib/elastic_whenever/task.rb
- spec/cli_spec.rb
- spec/task_spec.rb
- spec/tasks/rule_spec.rb
Fixes #15 
Whenever handles `bundle exec` prefix with the presence or absence of `Gemfile`. However, elastic whenever cannot know whether `Gemfile` exists or not. So add `bundle exec` by default, Make it unspecified with `bundle_command` option.
```ruby
set :bundle_command, ""
```
> Handling `bundle exec`

- lib/elastic_whenever/cli.rb
- lib/elastic_whenever/schedule.rb
- spec/cli_spec.rb
- spec/schedule_spec.rb
The `environment` is used to build the command but doesn't refer to the value set later...
> Fix bug for setting environments via CLI

- lib/elastic_whenever/schedule.rb
- spec/schedule_spec.rb
By default, since the execution timing is the default, December 1 is set as the default.
> Set default time for Chronic

- .travis.yml
Hi! We develop [SideCI](https://sideci.com), and we use the gem. Thank you!
We want to update using Ruby version to 2.5.0 that is in our application.
So, I'd like to add a CI matrix that is for Ruby 2.5 to the gem.
> CI against Ruby 2.5

- lib/elastic_whenever/option.rb
Because `File.exists?` is deprecated.
```bash
$ ruby -e File.exists?("a")
-e:1: warning: File.exists? is a deprecated name, use File.exist? instead
```
> Use `File.exist?` instead of `File.exists?`

- lib/elastic_whenever/schedule.rb
Our `schdule.rb` is like  a below that works with `whenever` gem.
```ruby
if environment ==  'qa'
every 30.minutes do
rake 'task_qa'
end
else 
every 30.minutes do
rake 'task_production'
end
end
```
But when I tried to use elastic_whenever, it said `[warn] Skipping unsupported method: environment`.
This pull request make it work.
> add `attr_reader :enviroment`

- lib/elastic_whenever/task/role.rb
- spec/tasks/role_spec.rb
I got  a error of `Aws::IAM::Errors::NoSuchEntity: Role not found for ecsEventsRole` during creating the scheduled tasks. 
It looks like `Task::Role#exists?` always return `true`. Because  `Aws::IAM::Resource#role` always return `AWS::IAM::Role` object.
> fix: `Task::Role#exists?` always return true.

- lib/elastic_whenever/cli.rb
- lib/elastic_whenever/option.rb
- lib/elastic_whenever/schedule.rb
- lib/elastic_whenever/task.rb
- lib/elastic_whenever/task/target.rb
- lib/elastic_whenever/version.rb
- spec/cli_spec.rb
- spec/schedule_spec.rb
- spec/task_spec.rb
- spec/tasks/rule_spec.rb
- spec/tasks/target_spec.rb
Made a quick attempt to get this gem working with FARGATE launch type. example usage:
```
elastic_whenever --region us-west-2 --launch_type FARGATE --security_groups sg-2c503655,sg-72f0cb0a --subnets subnet-4973d63f,subnet-45827d1d --update <MY_SERVICE>
```
Happy to polish this up further if you have any suggestions.
See: https://aws.amazon.com/about-aws/whats-new/2018/08/aws-fargate-now-supports-time-and-event-based-task-scheduling/
> update elastic_whenever for FARGATE launch type

- elastic_whenever.gemspec
See https://github.com/aws/aws-sdk-ruby/commit/43687b4ce5c670ad5491cce52a99994d1cdbc9e0
Fargate launch type is supported only 1.5 or later.
> Bump aws-sdk-cloudwatchevents dependency

- README.md
- lib/elastic_whenever/cli.rb
- lib/elastic_whenever/option.rb
- lib/elastic_whenever/schedule.rb
- spec/cli_spec.rb
- spec/option_spec.rb
- spec/schedule_spec.rb
Previously, basic ECS params are passed from variables in a schedule file. This was worthwhile making it possible to write all configurations in the schedule file. However, this approach is not good in order to pass complicated options like Fargate.
In this pull request, schedule file focus on Whenever's features, and ECS params are passed from arguments. This is a breaking change, but it is important for consistency of design.
> Pass ECS params as an argument

- lib/elastic_whenever/option.rb
- lib/elastic_whenever/task/target.rb
- spec/option_spec.rb
- spec/tasks/target_spec.rb
- Make security groups and subnets empty arrays
- Define `ecs_parameters` as a method
- Add test case for Fargate launch type
> Revise task's target

- .travis.yml
- elastic_whenever.gemspec
- lib/elastic_whenever.rb
- lib/elastic_whenever/cli.rb
When CloudWatch events are modified at the same time, sometimes the following exception is raised:
```
$ elastic_whenever --cluster example --task-definition example_oneoff --container oneoff --set environment=production -i example 
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.59.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Aws::CloudWatchEvents::Errors::ConcurrentModificationException 
from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.59.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call' 
from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.59.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call' 
from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.59.0/lib/aws …
```
> Retry for concurrent modification

- lib/elastic_whenever/cli.rb
I noticed a small typo when running the clear command, so thought I'd raise a PR to fix it.
> Fix typo in clear task log line

- lib/elastic_whenever/task/rule.rb
- spec/tasks/rule_spec.rb
This PR fixes an issue we ran into when using `elastic_whenever`: multiple rule blocks with the same commands and different timing expressions would not get created, since the rule name hashes collide.
(We've got a lot of tasks we need to run on multiple schedules.)
> Add expression to task rule name hash computation

- README.md
- lib/elastic_whenever/option.rb
- lib/elastic_whenever/task/role.rb
- spec/option_spec.rb
- spec/tasks/role_spec.rb
This allows the IAM role used for CloudWatch Events rules to be changed
from the default, also making it easier to define the role elsewhere
(e.g. Terraform, CloudFormation) and have elastic_whenever use a
named existing one.
> Make CloudWatch Events IAM role name configurable

- lib/elastic_whenever/task/rule.rb
- spec/tasks/rule_spec.rb
Hey,
I had a usecase where I was trying to get the CW Rule metrics from the command. This should add a bit more information to the description field to make searching in the console a bit easier.
> Add description to CloudWatch rule

- README.md
- lib/elastic_whenever/option.rb
- lib/elastic_whenever/task/rule.rb
- spec/option_spec.rb
- spec/tasks/rule_spec.rb
This PR adds an option to deploy the tasks but with the options disabled. We have a use case where we would like to migrate from whenever to elastic_whenever but want to avoid multiple executions from multiple environments.
Please let me know what you think.
> Add option to disable rule

- elastic_whenever.gemspec
Bump rake dependencies to avoid Ruby 2.7 warnings.
> Bump rake development dependency

- CHANGELOG.md
- lib/elastic_whenever/task/rule.rb
- lib/elastic_whenever/version.rb
When fetching all tasks ensure that the existing AWS Client is passed to the new task object and re-used this prevents a lookup for credentials for every task. Otherwise if you have lots of tasks and you run inside ECS  as task for example you will hit the rate limit asking for new credentials as each new client that is created makes a new call.
This rate limit on ECS appears to be a burst of 60 and steady rate of 40 per second.
This PR fixes the issue by passing in the already created AWS client to the new task objects created as part of the fetch operation.
> Fix API limit issue

- .github/workflows/build.yml
And this PR migrates setup action to `ruby/setup-ruby` from `actions/setup-ruby` because the action will be deprecated. See https://github.com/actions/setup-ruby/issues/80
> CI against Ruby 3.0

- elastic_whenever.gemspec
See also https://github.com/aws/aws-sdk-ruby/pull/2459#discussion_r552967179
Ruby 3.0 build is failing because rexml is now bundled gem and aws-sdk-ruby requires to add XML parser dependency explicitly.
https://github.com/wata727/elastic_whenever/runs/1712170050
```
An error occurred while loading ./spec/schedule_spec.rb.
Failure/Error: require "aws-sdk-ecs"
RuntimeError:
Unable to find a compatible xml library. Ensure that you have installed or added to your Gemfile one of ox, oga, libxml, nokogiri or rexml
```
> Add the rexml dependency explictly

- .github/workflows/build.yml
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/
> CI against Ruby 3.1

- .github/workflows/build.yml
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
> CI against Ruby 3.2

- .github/workflows/build.yml
https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/
> CI against Ruby 3.3

- lib/elastic_whenever/schedule.rb
- spec/schedule_spec.rb
Hello
I got a error when using cron syntax. In the day of week conversion, an exception occurs when it becomes divisible by and turns into 0.
ex). (6+1) % 7 = 0 
`Aws::CloudWatchEvents::Errors::ValidationException: Parameter ScheduleExpression is not valid`
```
every '30 1,8 * * 0,1,4,5,6' do
runner 'Example.execute'
end
```
`cron(30 1,8 ? * 1,2,5,6,0 *)`
> Fix week converion issue in cron syntax.
